### PR TITLE
Support for single NativeTest feature file added

### PR DESCRIPTION
**Pull request by Rabursky**

### CODE REVIEW

**Comment by kerrmarin** [comment]
Hey @Rabursky, thanks for working on this! Do you mind adding a test for this scenario so we can better see the use case? Also, if this is something you have encountered and didn't see any documentation for, would you mind adding a bit of text on the readme file so other users know about this functionality?

Thanks again!

**Comment by Rabursky** [comment]
Sure, no problem :)
Will add couple of commits during the week!

**Comment by Rabursky** [comment]
Hey @kerrmarin, I have updated the PR with example test. Should be enough to have a grasp of what's the feature all about.
Thanks!

**Comment by kerrmarin** [comment]
Looks good, can you merge the last changes from master into this branch so we can merge it in?

**Comment by Rabursky** [comment]
@kerrmarin Sure, done! :)

**Comment by kerrmarin** [comment]
Thanks @Rabursky ! 🎉

**Pull request merged**
