### PR TITLE
Set up before scenario feature added

### PR DESCRIPTION
**Pull request by Rabursky**
Pretty much simple feature that I was missing :)
It is very important to reset all state before perfoming next scenario.

### CODE REVIEW

**Comment by kerrmarin** [comment]
Awesome! Thanks for working on this @Rabursky. I've got a couple of questions.

Is this not something that can be done via `XCTestCase's` `setUp()` method? If it can, it would be my preference as that's the de-facto way to run code before each test and users of this library will be more familiar with that.

If I understand this correctly the way we've solved this at Net-A-Porter is to subclass `XCTestCase` and override the `setUp()` method to do our setup before every test then every feature file inherits from our `XCTestCase` subclass. Perhaps @nap-sam-dean has some opinion on this?

**Comment by Rabursky** [comment]
@kerrmarin Looks like it can be done but we would have to make some refactor. Currently the test relies on `func testRunNativeTests()` implemented in `NativeTestCase` hence `setUp()` method gets invoked only once during the execution of the TestCase.
We could totally make use of `public class func defaultTestSuite() -> XCTestSuite` to create custom, on-the-fly tests instead of hack-creating them using swizzling features of ObjC.
I am totally willing to do that, but still would like to ask you guys to merge this as a temporary solution.
Thanks

**Comment by kerrmarin** [comment]
@Rabursky that sounds fair. I've just pushed a small change to master if you can merge that in we will merge this change in.

**Comment by Rabursky** [comment]
@kerrmarin Done! Back to you :)

**Comment by kerrmarin** [comment]
Thanks! 🎉

**Pull request merged**
