### PR TITLE
Fixed accessing invocation property on test methods called directly

### LINKED ISSUE #103: Unable to call test method from another method
Hi, I have found an issue during writing tests using Gherkin. I need to call multiple test methods from one single method but it crashes here with unexpected `nil` in `self.invocation`

```swift
let rawName = String(describing: self.invocation!.selector)
```

I have test func with this body

```swift
    func testUsingsFunctions() {
        let login = GherkinLogin()
        login.testLoginSuccess()
        
        let payments = GherkinPayments()
        payments.testPaymentDetail()
    }
```
and calling method in this class
```swift
import XCTest
import XCTest_Gherkin

class GherkinLogin: XCTestCase {
    
    //MARK: Test cases
    func testLoginSuccess() {
        Given("Launched app")
        When("I fill password qawsed")
        Then("I tap on Login button")
        And("I see toolbar with title After login")
    }
}
```

is here any solution?

Thanks a lot! 🙌

### PR DESCRIPTION
**Pull request by ilyapuchka**
Resolves #103
When methods of test case are called from another test they don't have associated invocation.

### CODE REVIEW

**Comment by kerrmarin** [comment]
This fixes the crash but doesn't it cause tests to not run and no error is emitted? If that's the case I think we should throw an error or otherwise inform the user that the test isn't running as expected.

**Comment by ilyapuchka** [comment]
I think in invocation is nil when the test is invoked by XCTest then there is a bug in XCTest. I'm not sure if there is a better way to distinguish between test methods being invoked by XCTest or manually?

**Comment by kerrmarin** [comment]
Hey, sorry I might not be understanding the change enough but on the original issue (#103) the user says that their test crashes with a `nil` invocation so if we implement this change, instead of a crash, the test will not run, and the user won't get any feedback, is that correct?

**Comment by ilyapuchka** [comment]
@kerrmarin the issue happens when invoking test method from another test case, created manually, from another test method in another test case, created by Xcode when running test, not when running test itself.

**Pull request merged**
