### PR TITLE
Update travis to include Xcode12 / iOS 14

### PR DESCRIPTION
**Pull request by deanWombourne**

### CODE REVIEW

**Review by kerrmarin — APPROVED** [review]

**Comment by deanWombourne** [comment]
@kerrmarin Now all i have to do is work out what's going on with travis :(

**Comment by kerrmarin** [comment]
@deanWombourne:
```
    - WARN  | [XCTest-Gherkin/Core,XCTest-Gherkin/Native] xcodebuild:  /Users/travis/build/net-a-porter-mobile/XCTest-Gherkin/Pod/Core/XCTestCase+Gherkin.swift:67:14: warning: 'recordFailure(withDescription:inFile:atLine:expected:)' is deprecated: Replaced by 'record(_:)'

    - WARN  | [XCTest-Gherkin/Core,XCTest-Gherkin/Native] xcodebuild:  /Users/travis/build/net-a-porter-mobile/XCTest-Gherkin/Pod/Core/XCTestCase+Gherkin.swift:69:18: warning: 'recordFailure(withDescription:inFile:atLine:expected:)' is deprecated: Replaced by 'record(_:)'
```

**Comment by deanWombourne** [comment]
Yea, getting my head round the replacement method.

**Comment by deanWombourne** [comment]
So, replacement method is only in Xcode 14, but I can't see a way to check which xcode is running. Sigh. --allow-warnings it is :)

**Comment by kerrmarin** [comment]
😂

**Review by kerrmarin — APPROVED** [review]

**Review by benjdum59 — APPROVED** [review]

**Comment by deanWombourne** [comment]
Sigh close/open to poke travis to recheck the pr merge commit.

**Pull request merged**
