### PR TITLE
Partially matching expressions fix

### PR DESCRIPTION
**Pull request by Rabursky**
Just a small fix to the issue I was stumbling upon.
I had "I select all checks but bodywork" step in the scenarios (but not in StepDefiner) and the framework was matching it against similar step definition: "I select all checks" instead of throwing a fatalError.

### CODE REVIEW

**Comment by nap-sam-dean** [comment]
Hi,

This is actually expected - if you want a step to be an exact match then you can define it using line start and end anchors like this: `step("^I select all checks$")`.

The library should also remove ambiguity by failing immediately if it finds more than one matching step.

i.e. with the step definitions
```swift
step("I select all checks") { ... }
step("I select all checks but bodywork") { ... }
```

and a feature with this step in:
```swift
Given("I select all checks but bodywork")
```

Here, using the anchors on the first step will remove that ambiguity.

This should fail, with an error message showing that there are duplicate matching steps. If that's not happening for you then that's definitely a bug we should fix!

**Comment by Rabursky** [comment]
Hi,
I forgot to specify that I am using XCTest-Gherkin/Native. In this case I simply can't use `step("^I select all checks$")`.

**Comment by nap-sam-dean** [comment]
That should still work - you add the `^` and `$` in your StepDefiner, not in the feature file, so where the feature originally comes from shouldn't be an issue.

If I've misunderstood can you add an example and a test to your pull request please?

**Comment by Rabursky** [comment]
Ok, I get it. I am withdrawing the PR. Using `^` and `$` works okay.
It would be great to introduce some smarter matching than "first working" later on tho.
Thanks!

**Pull request closed without merging**
