### PR TITLE
#58 - Add swiftlint

### LINKED ISSUE #58: Add swiftlint* to keep coding style consistent
\* or similar

### PR DESCRIPTION
**Pull request by kerrmarin**
Adds swiftlint to the project. I went with adding it via cocoapods because it allows us to track the version we're using. I didn't change any of the source code and instead opted for adding all rules that triggered warnings/errors to the swiftlint.yml file. We can create PRs for removing each of these rules as necessary from the yaml file so it's easy to review.

Fixes #58

### CODE REVIEW

**Comment by deanWombourne** [comment]
Like it :) Do you want to add a stage to the travis.yml as well so we lint on the CI (passing in `--strict` to make warning as errors)? You can also add it as a post-build script in the example project so it shows the warnings in Xcode :)

**Comment by deanWombourne** [comment]
(PS +1 for adding it as a pod)

**Comment by kerrmarin** [comment]
I had it as a build step, but I've moved it into a script in a folder to make it more obvious. Since it's a build step, it'll run as part of travis when it builds the Example project so I think we don't need to change the travis config (unless we want to lint before build?) 👍

**Comment by deanWombourne** [comment]
It's going to be very annoying trying to develop with --strict on each build :) I would use the CO (or TRAVIS) variable set by travis to enable / disable the `--strict` option in the script - https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

**Comment by nap-sam-dean** [comment]
Nice :)

**Pull request merged**
